<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DU</name>
   <tag></tag>
   <elementGuidId>db46cb49-51d1-4f0c-80bf-a886cfd44dd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.circle-icon-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='Top']/nav/div/div[3]/ul/li[2]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>circle-icon-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Top&quot;)/nav[@class=&quot;main-navigation dw-mod&quot;]/div[@class=&quot;center-container top-container__center-container grid   dw-mod&quot;]/div[@class=&quot;u-flex dw-mod&quot;]/ul[@class=&quot;menu u-flex dw-mod&quot;]/li[@class=&quot;menu__item menu__item--horizontal menu__item menu__item--icon menu__item--top-level u-hidden-xxs is-dropdown is-dropdown--no-icon dw-mod&quot;]/div[@class=&quot;menu__link menu__link--icon dw-mod&quot;]/a[@class=&quot;u-color-inherit&quot;]/div[@class=&quot;circle-icon-btn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='Top']/nav/div/div[3]/ul/li[2]/div/a/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JasonScottTest2'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event calendar'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DU']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
   </webElementXpaths>
</WebElementEntity>
